#!/bin/bash
set +x

printf  "Enter username: "
read USERNAME
printf "Enter SSH port: "
read SSH_PORT

adduser --gecos "" $USERNAME
adduser $USERNAME sudo

mkdir /home/$USERNAME/.ssh
cp ~/.ssh/authorized_keys /home/$USERNAME/.ssh/
chown --recursive $USERNAME /home/${USERNAME}.ssh/

sed -i "/Port / {
s/^#//
s/ 22/ #{SSH_PORT}/
}" /etc/ssh/sshd_config

sed -i "/PermitRootLogin / {
s/^#//
s/ yes/ no/
}" /etc/ssh/sshd_config

sed -i "/PasswordAuthentication / {
s/^#//
s/ yes/ no/
}" /etc/ssh/sshd_config

ufw allow $SSH_PORT/tcp
ufw delete allow 22

systemctl restart sshd
cd /home/$USERNAME
su $USERNAME
